CREATE DATABASE IF NOT EXISTS RedSkyApp;
USE RedSkyApp;

-- upsert
CREATE TABLE IF NOT EXISTS `Devices` (
  `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AccountId` INT UNSIGNED DEFAULT NULL,
  `MobileId` CHAR(20) NOT NULL UNIQUE,
  `IMEI` CHAR(15) NULL,
  `ICCID` CHAR(20) NULL,
  `Firmware` CHAR(8) DEFAULT NULL,
  `Script` CHAR(10) DEFAULT NULL, 
  `Notes` VARCHAR(1024) DEFAULT NULL,
  `CreatedDate` DATETIME(3) DEFAULT NULL,
  `LastUpdate` DATETIME(3) DEFAULT NULL,
  `Archived` TINYINT(1) NOT NULL DEFAULT 0,
  `ArchivedDate` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- upsert
CREATE TABLE IF NOT EXISTS `DeviceMeta` (
  `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MobileId` CHAR(20) NOT NULL UNIQUE,
  `ScriptVersion` CHAR(10) DEFAULT '( , )',
  `AppId` INT NOT NULL DEFAULT -1,
  `AppVersion` CHAR(20) NOT NULL DEFAULT '( , , , )',
  `VehicleClass` INT NOT NULL DEFAULT 0,
  `HttpOtaUpdateStatusOk` TINYINT(1) NOT NULL DEFAULT 1,
  `GpsAntennaStatusOk` TINYINT(1) NOT NULL DEFAULT 1,
  `GpsReceiverTestOk` TINYINT(1) NOT NULL DEFAULT 1,
  `GpsReceiverTracking` TINYINT(1) NOT NULL DEFAULT 1,
  `ModemSelection` INT NOT NULL DEFAULT 0,
  `MobileIdType` INT NOT NULL DEFAULT 1,
  `QueryId` INT NOT NULL DEFAULT 0,
  `ESN` CHAR(20) DEFAULT NULL,
  `IMEI` CHAR(15) DEFAULT NULL,
  `IMSI` CHAR(15) DEFAULT NULL,
  `MobileIdentificationNumber` CHAR(12) DEFAULT NULL,
  `ICCID` CHAR(20) DEFAULT NULL,
  `CreatedDate` DATETIME(3) NOT NULL,
  `LastUpdate` DATETIME(3) DEFAULT NULL,
  `Archived` TINYINT(1) NOT NULL DEFAULT 0,
  `ArchivedDate` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- insert only
CREATE TABLE IF NOT EXISTS `DeviceLogs` (
 `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `MobileId` CHAR(20) NOT NULL,
 `PacketData` VARCHAR(1024) NOT NULL,
 `PacketIp` CHAR(20) NOT NULL,
 `PacketPort` INTEGER NOT NULL,
 `CreatedDate` DATETIME(3) NOT NULL,
 PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- upsert
CREATE TABLE IF NOT EXISTS `DeviceTelemetry` (
   `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `MobileId` CHAR(20) NOT NULL UNIQUE,
   `Latitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
   `Longitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
   `Speed` INTEGER NOT NULL DEFAULT 0,
   `Heading` INTEGER NOT NULL DEFAULT 0,
   `Odometer` INTEGER NOT NULL DEFAULT 0,
   `VirtualOdometer` INTEGER NOT NULL DEFAULT 0,
   `EngineHours` INT NOT NULL DEFAULT 0,  
   `GPIO_01` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_02` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_03` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_04` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_05` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_06` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_07` TINYINT(1) NOT NULL DEFAULT 0,
   `GPIO_08` TINYINT(1) NOT NULL DEFAULT 0,
   `Accumulator_01` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_02` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_03` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_04` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_05` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_06` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_07` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_08` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_09` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_10` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_11` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_12` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_13` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_14` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_15` INTEGER NOT NULL DEFAULT 0,
   `Accumulator_16` INTEGER NOT NULL DEFAULT 0,
   `CreatedDate` DATETIME(3) NOT NULL,
   PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- upsert
CREATE TABLE IF NOT EXISTS `Assets` (
   `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `AccountId` INT UNSIGNED DEFAULT NULL,
   `GroupId` INT UNSIGNED DEFAULT NULL,
   `MobileId` CHAR(20) NOT NULL UNIQUE,
   `VIN` CHAR(17) DEFAULT NULL,
   `Year` INTEGER DEFAULT NULL,   
   `Name` CHAR(128) DEFAULT NULL, 
   `Label` CHAR(64) DEFAULT NULL,
   `MiniLabel` CHAR(16) DEFAULT NULL,
   `LastEpoch` INT UNSIGNED NOT NULL DEFAULT 0,
   `LastState` INTEGER NOT NULL DEFAULT -1,   
   `LastEvent` INT UNSIGNED DEFAULT NULL,
   `LastLatitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
   `LastLongitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
   `LastSpeed` INTEGER NOT NULL DEFAULT 0,
   `LastHeading` INTEGER NOT NULL DEFAULT 0,
   `Odometer` INTEGER NOT NULL DEFAULT 0,
   `EngineHours` INT NOT NULL DEFAULT 0,  
   `LastLocation` CHAR(128) DEFAULT NULL,  
   `CreatedDate` DATETIME(3) DEFAULT NULL,
   `LastUpdate` DATETIME(3) DEFAULT NULL,
   `Archived` TINYINT(1) NOT NULL DEFAULT 0,
   `ArchivedDate` DATETIME(3) DEFAULT NULL,
   PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- insert
CREATE TABLE IF NOT EXISTS `ActivityLog` (
 `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `MobileId` CHAR(20) NOT NULL,
 `Activity` INT UNSIGNED NOT NULL, -- only a few activity options
 `Description` VARCHAR(1024) NULL,
 `StartTime` DATETIME(3) DEFAULT NULL,
 `EndTime` DATETIME(3) DEFAULT NULL,
 `StartLatitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `StartLongitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `EndLatitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `EndLongitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `Odometer` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `Landmarks` (
    `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `AccountId` INT UNSIGNED NOT NULL,
    `GroupId` INT UNSIGNED NOT NULL,
    `Label` VARCHAR(64) NOT NULL,
    `Address` VARCHAR(64) NOT NULL,
    `City` VARCHAR(64) NOT NULL,
    `State` CHAR(2) NOT NULL,
    `Zip` CHAR(11) NOT NULL,
    `Country` VARCHAR(64) NOT NULL DEFAULT 'USA',
    `GeoFence` GEOMETRY, -- change to NOT NULL on API sync
    `Latitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
    `Longitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
    `TriggerProximity` INT UNSIGNED NOT NULL DEFAULT 0,
    `TriggerParkRequired` TINYINT(1) NOT NULL DEFAULT 0,
    `CreatedDate` DATETIME(3) DEFAULT NULL,
    `LastUpdate` DATETIME(3) DEFAULT NULL,
    `Archived` TINYINT(1) NOT NULL DEFAULT 0,
    `ArchivedDate` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`RecordId`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `LandmarkActivity` (
 `RecordId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `LandmarkId` INT NOT NULL DEFAULT 0,
 `MobileId` CHAR(20) NOT NULL,
 `ArrivalTime` DATETIME(3) DEFAULT NULL,
 `DepartureTime` DATETIME(3) DEFAULT NULL,
 `Proximity` INT NOT NULL DEFAULT 0,
 `StartLatitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `StartLongitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `EndLatitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `EndLongitude` DECIMAL(11,9) NOT NULL DEFAULT 0,
 `Odometer` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`RecordId`)
  )ENGINE=InnoDB DEFAULT CHARSET=latin1;

/* INSERT INTO Landmarks (AccountId, GroupId, Label, Address, City, State, Zip, Country, Latitude, Longitude, TriggerProximity, TriggerParkRequired, Archived) VALUES (1, 1, '11 State Street', '11 State Street', 'Newburgh', 'IN', '47630', 'USA', -87.40529, 37.94449, 100, 0, 0); */
